apiVersion: v1
data:
  address: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAyVVdVTkU1UlMvQjA0MUQzU1BVMlcvNUxXM3VrOGZrTDVncTN5R2tneTNxUGxN
kind: Secret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
