 creation_rules:
 - path_regex: .*.yaml
   encrypted_regex: ^(data|stringData)$
   # gcp_kms: "projects/dx-somtoxhi/locations/global/keyRings/sops-demo/cryptoKeys/sops-demo-key"
   pgp: 22FE5F30631096FFEE7F1E9B40803ABF3FE40332

