---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  decryption:
    provider: sops
  interval: 1h0m0s
  path: ./infra/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-stack
  interval: 1h0m0s
  path: ./infra/monitoring-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m0s
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  decryption:
    provider: sops
  interval: 10m0s
  path: ./infra/tailscalexx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
