apiVersion: v1
data:
    address: ENC[AES256_GCM,data:z8Oa9Tt4CTkJDJuIRzw7zs5lYHeQyXBPze0nJgupGZFj6rtdvyE1T/FWnXBos5MmZEapzA+gaZW3bpS1kDGH/abEOnu60Tu7eFqi4I1fmftULvhKR54sC3Z13cN6t+SQHR9XLVcwYHcq2Hg5,iv:imh1PPp4EmRJgcLgNRladZpLFBAAfFKM0+6wnrL3Ltw=,tag:U26s0ok2zF5/PrWEBEYrTQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: slack-url
    namespace: monitoring
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/dx-somtoxhi/locations/global/keyRings/sops-demos/cryptoKeys/sops-demo-key
        created_at: '2022-10-18T14:43:20Z'
        enc: CiQAStUHEYX9f5PpoHlhQcmAdDbn/AQSIj0XH69grVG8QAvmOL8SSQAiFejMRScwyqJN/c0As1p5F7P276o/NvoGfMyvKYurr8wHjPNQPkJw9K/XJ7i7C3VHWPIcgcMS6U3uAEyxdRbEfZf7hs2L01k=
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-10-18T14:43:22Z'
    mac: ENC[AES256_GCM,data:9io73tp95Y0NGrCBACXlpdJpn6ZhKXQHueMcSf8dthNiq/0wGXIjkhhlr1HPeMdnambPer3zDm7GECE0eBXOD2HTyA6d9hzPQC6lN6078f4ZZI7orFRQnhwk8IMXcLSFrDWem32uA9I7poL4HuoJk5pLXn24adOwXLe6BUlRBe4=,iv:foNB3yAzkllQKdfMCOOt/gxxxLHffHTMcCIaOYBCqUc=,tag:5XkXU4w+yt5oCI0Z4KK3pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
