---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-system
  namespace: flux-system
spec:
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: OCIRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: HelmRelease
    name: '*'
    namespace: monitoring
  - kind: HelmRelease
    name: '*'
    namespace: tailscale
  - kind: HelmRelease
    name: '*'
    namespace: pl
  providerRef:
    name: slack

