apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: tailscale
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - get
  - update
